# Site Info
title:              "Eudemonis"
description:        "A personal blog about finding the truth through philosophy, science, spiritualism and shamanism"
author_name:        "Eudemonis" # change this to your name
logo_url:           "" # Get it from GitHub API: https://api.github.com/users/<username>

# Site Settings
url:                https://eudemonis.github.io # main url
baseurl:             #Name of the repository
permalink:          /:title # Post permalink
timezone:           Europe/Paris # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            false  # enables support for mathjax - set to 'false' to disable
disqus_baseurl: "https://eudemonis.github.io/"
disqus_shortname: https-eudemonis-github-io

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
